--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    active boolean,
    copies integer,
    pages integer,
    id bigint NOT NULL,
    uploaded_by character varying(20),
    file_type character varying(50),
    storage_path character varying(500),
    original_name character varying(255),
    CONSTRAINT attachments_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['PDF'::character varying, 'DOC'::character varying, 'DOCX'::character varying, 'PNG'::character varying, 'JPG'::character varying, 'PPT'::character varying, 'ODT'::character varying, 'TXT'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    client_id bigint NOT NULL,
    registered_at timestamp(6) without time zone,
    store_id bigint NOT NULL,
    status character varying(255),
    CONSTRAINT clients_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying, 'PENDING_APPROVAL'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configurations (
    active boolean,
    cost_impact double precision,
    id bigint NOT NULL,
    store_id bigint,
    type character varying(255),
    value character varying(255)
);


--
-- Name: configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configurations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contacts (
    client_id bigint,
    id bigint NOT NULL,
    last_activity timestamp(6) without time zone,
    store_id bigint,
    display_name character varying(255),
    phone_number character varying(255),
    profile_photo character varying(255),
    status character varying(255),
    CONSTRAINT contacts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'VERIFIED'::character varying, 'UNVERIFIED'::character varying, 'BOUNCED'::character varying, 'OPTED_OUT'::character varying, 'BLOCKED'::character varying, 'DUPLICATE'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    created_at timestamp(6) without time zone,
    customer_contact_id bigint,
    customer_service_phone_id bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone
);


--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: copypoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.copypoints (
    created_at timestamp(6) without time zone,
    created_by_id bigint NOT NULL,
    id bigint NOT NULL,
    last_modified_at timestamp(6) without time zone,
    responsible_id bigint,
    store_id bigint,
    name character varying(255),
    status character varying(255),
    CONSTRAINT copypoints_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: copypoints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.copypoints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.copypoints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_service_phones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_service_phones (
    copypoint_id bigint,
    id bigint NOT NULL,
    phone_number character varying(255)
);


--
-- Name: customer_service_phones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_service_phones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_service_phones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_roles (
    added_at timestamp(6) without time zone,
    copypoint_id bigint,
    employee_id bigint,
    id bigint NOT NULL,
    role_id bigint,
    store_id bigint
);


--
-- Name: employee_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    last_modified_at timestamp(6) without time zone,
    registered_at timestamp(6) without time zone,
    registered_by bigint,
    user_id bigint,
    status character varying(50),
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ON_LEAVE'::character varying, 'SUSPENDED'::character varying, 'TERMINATED'::character varying, 'PENDING_START'::character varying, 'PROBATION'::character varying, 'RETIRED'::character varying])::text[])))
);


--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materials (
    active boolean,
    min_stock integer,
    stock integer,
    unit_price double precision,
    id bigint NOT NULL,
    store_id bigint,
    unit_base character varying(20),
    unit_purchase character varying(20),
    name character varying(50),
    description character varying(255)
);


--
-- Name: materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mercadopago_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mercadopago_configs (
    id bigint NOT NULL,
    copypoint_id bigint,
    access_token_encrypted character varying(1000) NOT NULL,
    public_key_encrypted character varying(1000) NOT NULL,
    client_secret_encrypted character varying(1000) NOT NULL,
    webhook_secret_encrypted character varying(1000) NOT NULL,
    client_id character varying(200) NOT NULL,
    is_sandbox boolean DEFAULT true,
    is_active boolean DEFAULT true,
    vendor_email character varying(200),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: mercadopago_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.mercadopago_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: mercadopago_configs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.mercadopago_configs_id_seq OWNED BY public.mercadopago_configs.id;


--
-- Name: message_attachment_urls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_attachment_urls (
    message_id bigint NOT NULL,
    attachment_url character varying(500)
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    conversation_id bigint,
    id bigint NOT NULL,
    direction character varying(255),
    message_sid character varying(255),
    status character varying(255),
    date_sent timestamp without time zone,
    date_delivered timestamp without time zone,
    date_read timestamp without time zone,
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_updated timestamp without time zone,
    CONSTRAINT messages_direction_check CHECK (((direction)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying])::text[]))),
    CONSTRAINT messages_status_check CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'DELIVERED'::character varying, 'READ'::character varying, 'FAILED'::character varying, 'QUEUED'::character varying, 'SENDING'::character varying, 'UNDELIVERED'::character varying, 'UNKNOWN'::character varying, 'PARTIALLY_DELIVERED'::character varying, 'REJECTED'::character varying, 'SCHEDULED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: COLUMN messages.date_sent; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.date_sent IS 'Date when the message was sent from Twilio (official message date)';


--
-- Name: COLUMN messages.date_delivered; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.date_delivered IS 'Date when the message was delivered to the recipient';


--
-- Name: COLUMN messages.date_read; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.date_read IS 'Date when the message was read by the recipient';


--
-- Name: COLUMN messages.date_created; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.date_created IS 'Date when the message was created in our system';


--
-- Name: COLUMN messages.date_updated; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.date_updated IS 'Date of the last update to the message';


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messaging_provider_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messaging_provider_configurations (
    id bigint NOT NULL,
    provider_type character varying(50) NOT NULL,
    is_active boolean DEFAULT true,
    display_name character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE messaging_provider_configurations; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.messaging_provider_configurations IS 'Base table for messaging provider configurations using JPA inheritance';


--
-- Name: COLUMN messaging_provider_configurations.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messaging_provider_configurations.id IS 'Primary key';


--
-- Name: COLUMN messaging_provider_configurations.provider_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messaging_provider_configurations.provider_type IS 'Discriminator column for JPA inheritance';


--
-- Name: COLUMN messaging_provider_configurations.is_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messaging_provider_configurations.is_active IS 'Flag to indicate if configuration is active';


--
-- Name: COLUMN messaging_provider_configurations.display_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messaging_provider_configurations.display_name IS 'Human readable name for the configuration';


--
-- Name: messaging_provider_configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.messaging_provider_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: messaging_provider_configurations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.messaging_provider_configurations_id_seq OWNED BY public.messaging_provider_configurations.id;


--
-- Name: modules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modules (
    active boolean NOT NULL,
    id bigint NOT NULL,
    parent_module_id bigint,
    name character varying(50) NOT NULL,
    description character varying(255)
);


--
-- Name: modules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_attempts (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    payment_id bigint,
    error_code character varying(255),
    gateway_response json,
    status character varying(255),
    CONSTRAINT payment_attempts_status_check CHECK (((status)::text = ANY ((ARRAY['INITIATED'::character varying, 'PENDING'::character varying, 'PROCESSING'::character varying, 'AWAITING_CONFIRMATION'::character varying, 'REQUIRES_ACTION'::character varying, 'SUCCEEDED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'DECLINED'::character varying, 'CANCELLED'::character varying, 'ABANDONED'::character varying, 'EXPIRED'::character varying, 'INSUFFICIENT_FUNDS'::character varying, 'INVALID_CARD'::character varying, 'AUTHENTICATION_FAILED'::character varying, 'FRAUD_DETECTED'::character varying, 'BLOCKED_BY_GATEWAY'::character varying, 'NETWORK_ERROR'::character varying, 'REFUND_PENDING'::character varying, 'REFUNDED'::character varying, 'DISPUTED'::character varying, 'UNDER_REVIEW'::character varying, 'FLAGGED'::character varying])::text[])))
);


--
-- Name: payment_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paymenth_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paymenth_methods (
    id bigint NOT NULL,
    description character varying(50)
);


--
-- Name: paymenth_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.paymenth_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paymenth_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    amount double precision,
    currency character varying(3),
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    payment_method_id bigint,
    sale_id bigint,
    status character varying(30),
    gateway_id character varying(255),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'DISPUTED'::character varying, 'EXPIRED'::character varying, 'AUTHORIZED'::character varying, 'CAPTURED'::character varying, 'VOIDED'::character varying, 'REJECTED'::character varying, 'ON_HOLD'::character varying, 'REQUIRES_ACTION'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    module_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: persons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persons (
    id bigint NOT NULL,
    phone_number character varying(15),
    first_name character varying(20),
    last_name character varying(20)
);


--
-- Name: persons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_configurations (
    configuration_id bigint NOT NULL,
    profile_id bigint NOT NULL
);


--
-- Name: profile_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_materials (
    obligatory boolean,
    quantity integer,
    material_id bigint NOT NULL,
    profile_id bigint NOT NULL,
    notes character varying(500)
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    active boolean,
    unit_price double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) without time zone,
    name character varying(50),
    description character varying(255)
);


--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(20)
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_profiles (
    quantity integer,
    subtotal double precision,
    unit_price double precision,
    attachment_id bigint,
    profile_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    currency character varying(3),
    discount double precision,
    total_sale double precision,
    copypoint_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    payment_method_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    status character varying(255),
    CONSTRAINT sales_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'PAYMENT_PENDING'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'ON_HOLD'::character varying, 'PARTIALLY_PAID'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_profiles (
    profile_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    active boolean,
    id bigint NOT NULL,
    store_id bigint,
    name character varying(70)
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stores (
    currency character varying(3),
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    owner_id bigint,
    name character varying(20)
);


--
-- Name: stores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: twilio_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twilio_configurations (
    id bigint NOT NULL,
    account_sid character varying(1000) NOT NULL,
    auth_token character varying(1000) NOT NULL,
    webhook_url character varying(255),
    status_callback_url character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE twilio_configurations; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.twilio_configurations IS 'Twilio-specific configuration extending MessagingProviderConfig';


--
-- Name: COLUMN twilio_configurations.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.twilio_configurations.id IS 'Primary key and foreign key to messaging_provider_configurations';


--
-- Name: COLUMN twilio_configurations.account_sid; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.twilio_configurations.account_sid IS 'Encrypted Twilio Account SID (AES encrypted)';


--
-- Name: COLUMN twilio_configurations.auth_token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.twilio_configurations.auth_token IS 'Encrypted Twilio Auth Token (AES encrypted)';


--
-- Name: COLUMN twilio_configurations.webhook_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.twilio_configurations.webhook_url IS 'Twilio webhook URL for incoming messages';


--
-- Name: COLUMN twilio_configurations.status_callback_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.twilio_configurations.status_callback_url IS 'Twilio status callback URL for message delivery status';


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    creation_date timestamp(6) without time zone,
    id bigint NOT NULL,
    person_id bigint,
    email character varying(50),
    password character varying(255),
    status character varying(255),
    username character varying(255),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying, 'UNDER_REVIEW'::character varying, 'BANNED'::character varying, 'PENDING_VERIFICATION'::character varying, 'SUSPENDED'::character varying, 'DEACTIVATED'::character varying, 'LOCKED'::character varying, 'PENDING_APPROVAL'::character varying, 'EXPIRED'::character varying, 'LIMITED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mercadopago_configs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mercadopago_configs ALTER COLUMN id SET DEFAULT nextval('public.mercadopago_configs_id_seq'::regclass);


--
-- Name: messaging_provider_configurations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messaging_provider_configurations ALTER COLUMN id SET DEFAULT nextval('public.messaging_provider_configurations_id_seq'::regclass);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id, store_id);


--
-- Name: configurations configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_pkey PRIMARY KEY (id);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: copypoints copypoints_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copypoints
    ADD CONSTRAINT copypoints_name_key UNIQUE (name);


--
-- Name: copypoints copypoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copypoints
    ADD CONSTRAINT copypoints_pkey PRIMARY KEY (id);


--
-- Name: customer_service_phones customer_service_phones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_service_phones
    ADD CONSTRAINT customer_service_phones_pkey PRIMARY KEY (id);


--
-- Name: employee_roles employee_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT employee_roles_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);


--
-- Name: mercadopago_configs mercadopago_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mercadopago_configs
    ADD CONSTRAINT mercadopago_configs_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: messaging_provider_configurations messaging_provider_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messaging_provider_configurations
    ADD CONSTRAINT messaging_provider_configurations_pkey PRIMARY KEY (id);


--
-- Name: modules modules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (id);


--
-- Name: payment_attempts payment_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_attempts
    ADD CONSTRAINT payment_attempts_pkey PRIMARY KEY (id);


--
-- Name: paymenth_methods paymenth_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paymenth_methods
    ADD CONSTRAINT paymenth_methods_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (module_id, role_id);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- Name: profile_materials profile_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_materials
    ADD CONSTRAINT profile_materials_pkey PRIMARY KEY (material_id, profile_id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sale_profiles sale_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_profiles
    ADD CONSTRAINT sale_profiles_pkey PRIMARY KEY (profile_id, sale_id, service_id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: stores stores_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_name_key UNIQUE (name);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: twilio_configurations twilio_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twilio_configurations
    ADD CONSTRAINT twilio_configurations_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



--
-- Name: idx_copypoint_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_copypoint_active ON public.mercadopago_configs USING btree (copypoint_id, is_active);


--
-- Name: idx_messages_conversation_date_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_conversation_date_created ON public.messages USING btree (conversation_id, date_created);


--
-- Name: idx_messages_date_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_date_created ON public.messages USING btree (date_created);


--
-- Name: idx_messages_date_delivered; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_date_delivered ON public.messages USING btree (date_delivered);


--
-- Name: idx_messages_date_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_date_read ON public.messages USING btree (date_read);


--
-- Name: idx_messages_date_sent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_date_sent ON public.messages USING btree (date_sent);


--
-- Name: idx_messages_date_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_date_updated ON public.messages USING btree (date_updated);


--
-- Name: idx_messaging_provider_config_is_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messaging_provider_config_is_active ON public.messaging_provider_configurations USING btree (is_active);


--
-- Name: idx_messaging_provider_config_provider_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messaging_provider_config_provider_type ON public.messaging_provider_configurations USING btree (provider_type);


--
-- Name: idx_twilio_config_status_callback_url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_twilio_config_status_callback_url ON public.twilio_configurations USING btree (status_callback_url);


--
-- Name: idx_twilio_config_webhook_url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_twilio_config_webhook_url ON public.twilio_configurations USING btree (webhook_url);


--
-- Name: unique_active_copypoint; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_active_copypoint ON public.mercadopago_configs USING btree (is_active, copypoint_id);


--
-- Name: service_profiles fk17wcpfymfa15704wvh8ym7260; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_profiles
    ADD CONSTRAINT fk17wcpfymfa15704wvh8ym7260 FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


--
-- Name: employee_roles fk1hurcf8qirwresow95868ad2u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk1hurcf8qirwresow95868ad2u FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: modules fk20dssmxngfogm3bvind75rytb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT fk20dssmxngfogm3bvind75rytb FOREIGN KEY (parent_module_id) REFERENCES public.modules(id);


--
-- Name: permissions fk22lamcef3kykumk5rwjiv4x5u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT fk22lamcef3kykumk5rwjiv4x5u FOREIGN KEY (module_id) REFERENCES public.modules(id);


--
-- Name: profile_materials fk295c03p18t4uwuxjb0cw1h1hj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_materials
    ADD CONSTRAINT fk295c03p18t4uwuxjb0cw1h1hj FOREIGN KEY (material_id) REFERENCES public.materials(id);


--
-- Name: employee_roles fk2qbj3ybgl2aqbi65t3l8ohuc4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk2qbj3ybgl2aqbi65t3l8ohuc4 FOREIGN KEY (copypoint_id) REFERENCES public.copypoints(id);


--
-- Name: employee_roles fk398vvu81xw154mvy3g2eytscn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk398vvu81xw154mvy3g2eytscn FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: copypoints fk3cb16tfh073ch6bddplrvtte3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copypoints
    ADD CONSTRAINT fk3cb16tfh073ch6bddplrvtte3 FOREIGN KEY (responsible_id) REFERENCES public.users(id);


--
-- Name: employee_roles fk3uwwaxeiucvfixgd45etkjgmg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk3uwwaxeiucvfixgd45etkjgmg FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: conversations fk55qf0f2rlg19mw1kre29j42k0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk55qf0f2rlg19mw1kre29j42k0 FOREIGN KEY (customer_contact_id) REFERENCES public.contacts(id);


--
-- Name: sales fk5bgaw8g0rrbqdvafq36g58smk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk5bgaw8g0rrbqdvafq36g58smk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: sales fk5ch1i93t4fmhy6bcc4pdhunha; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk5ch1i93t4fmhy6bcc4pdhunha FOREIGN KEY (copypoint_id) REFERENCES public.copypoints(id);


--
-- Name: stores fk62smc31fbgclsu56aa4y2hrxg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT fk62smc31fbgclsu56aa4y2hrxg FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: employees fk69x3vjuy1t5p18a5llb8h2fjx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk69x3vjuy1t5p18a5llb8h2fjx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: profile_configurations fk9uwff7ciq61wqp782pgsmb69o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_configurations
    ADD CONSTRAINT fk9uwff7ciq61wqp782pgsmb69o FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


--
-- Name: twilio_configurations fk_twilio_config_messaging_provider; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twilio_configurations
    ADD CONSTRAINT fk_twilio_config_messaging_provider FOREIGN KEY (id) REFERENCES public.messaging_provider_configurations(id) ON DELETE CASCADE;


--
-- Name: payment_attempts fka3a9tqynt8vtwcmq9q8igujra; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_attempts
    ADD CONSTRAINT fka3a9tqynt8vtwcmq9q8igujra FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: customer_service_phones fkb02kcc8g76svg8uhruw1cu4gn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_service_phones
    ADD CONSTRAINT fkb02kcc8g76svg8uhruw1cu4gn FOREIGN KEY (copypoint_id) REFERENCES public.copypoints(id);


--
-- Name: copypoints fkc0lwho7scqf9bkxvh8wjuxkxw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copypoints
    ADD CONSTRAINT fkc0lwho7scqf9bkxvh8wjuxkxw FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: clients fkckg7aj1rt9scui5ik5tr93d0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkckg7aj1rt9scui5ik5tr93d0 FOREIGN KEY (client_id) REFERENCES public.users(id);


--
-- Name: configurations fkeel2qq6hcf1yrdvnh82vmrdiv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT fkeel2qq6hcf1yrdvnh82vmrdiv FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: services fkerbk22vqq2ah7sbrmp7x0mfbh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT fkerbk22vqq2ah7sbrmp7x0mfbh FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: sale_profiles fkeueo0jdjv9v189350u6p2cd4u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_profiles
    ADD CONSTRAINT fkeueo0jdjv9v189350u6p2cd4u FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- Name: employees fkgg5t83qt2lmfqph42o3v1r4w6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fkgg5t83qt2lmfqph42o3v1r4w6 FOREIGN KEY (registered_by) REFERENCES public.users(id);


--
-- Name: permissions fkgop02n5f9b9a1e924hsjq4q7b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT fkgop02n5f9b9a1e924hsjq4q7b FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: profile_configurations fkhhg8e3k4u5h1apur96ehj1w08; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_configurations
    ADD CONSTRAINT fkhhg8e3k4u5h1apur96ehj1w08 FOREIGN KEY (configuration_id) REFERENCES public.configurations(id);


--
-- Name: profile_materials fkigj180fgcq7p9u6dt9owg3xqj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_materials
    ADD CONSTRAINT fkigj180fgcq7p9u6dt9owg3xqj FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


--
-- Name: clients fkjxl64x03ny1gn0q74wn0g4edn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkjxl64x03ny1gn0q74wn0g4edn FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: contacts fkkieq1tu4s2b2mmewr3w0u7ngv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT fkkieq1tu4s2b2mmewr3w0u7ngv FOREIGN KEY (client_id, store_id) REFERENCES public.clients(client_id, store_id);


--
-- Name: payments fkl5ax948m03dbdcy3i0aql4jil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkl5ax948m03dbdcy3i0aql4jil FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- Name: sale_profiles fklpswf6ger28cnax83huapjlyr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_profiles
    ADD CONSTRAINT fklpswf6ger28cnax83huapjlyr FOREIGN KEY (attachment_id) REFERENCES public.attachments(id);


--
-- Name: users fkmvbq8q4vpi6csivw9wcnq6ho5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkmvbq8q4vpi6csivw9wcnq6ho5 FOREIGN KEY (person_id) REFERENCES public.persons(id);


--
-- Name: materials fkmyh25ow8wioop4slvxaqfcif8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT fkmyh25ow8wioop4slvxaqfcif8 FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: sale_profiles fkne0c1vqsjn9u94kibh9q8uhpw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_profiles
    ADD CONSTRAINT fkne0c1vqsjn9u94kibh9q8uhpw FOREIGN KEY (profile_id) REFERENCES public.profiles(id);


--
-- Name: message_attachment_urls fko9k67rlm5gjghe4jkrstr12kv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_attachment_urls
    ADD CONSTRAINT fko9k67rlm5gjghe4jkrstr12kv FOREIGN KEY (message_id) REFERENCES public.messages(id);


--
-- Name: conversations fksayavglmhwr0drf9txbuuqa3i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fksayavglmhwr0drf9txbuuqa3i FOREIGN KEY (customer_service_phone_id) REFERENCES public.customer_service_phones(id);


--
-- Name: service_profiles fksevt1sn29v8wc6l1nakhax79f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_profiles
    ADD CONSTRAINT fksevt1sn29v8wc6l1nakhax79f FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: copypoints fkspppp45m0cxtl368wyq5rw91a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copypoints
    ADD CONSTRAINT fkspppp45m0cxtl368wyq5rw91a FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- Name: messages fkt492th6wsovh1nush5yl5jj8e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt492th6wsovh1nush5yl5jj8e FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: payments fkt6skr682pdidpcgq32ltuc1i2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkt6skr682pdidpcgq32ltuc1i2 FOREIGN KEY (payment_method_id) REFERENCES public.paymenth_methods(id);


--
-- Name: sales fktcbd0svhympmf5exodjjkou25; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fktcbd0svhympmf5exodjjkou25 FOREIGN KEY (payment_method_id) REFERENCES public.paymenth_methods(id);


--
-- Name: mercadopago_configs mercadopago_configs_copypoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mercadopago_configs
    ADD CONSTRAINT mercadopago_configs_copypoint_id_fkey FOREIGN KEY (copypoint_id) REFERENCES public.copypoints(id);


--
-- Name: sale_profiles sale_profiles_services_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_profiles
    ADD CONSTRAINT sale_profiles_services_fk FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- PostgreSQL database dump complete
--

